run-yaml:
	./build/install/app/bin/app src/test/resources/fixtures/complex1.yaml src/test/resources/fixtures/complex2.yaml
run-yml:
	./build/install/app/bin/app src/test/resources/fixtures/complex1.yml src/test/resources/fixtures/complex2.yml
run-json:
	./build/install/app/bin/app src/test/resources/fixtures/complex1.json src/test/resources/fixtures/complex2.json
run-help:
	./build/install/app/bin/app -h
run-ver:
	./build/install/app/bin/app -v
run-test:
	./gradlew test
