run-dist:
	./build/install/app/bin/app  src/main/resources/difficult1.json src/main/resources/difficult2.json

run-help:
	./build/install/app/bin/app -h
run-ver:
	./build/install/app/bin/app -v
