name: project-workflows
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10
      - run: app/.gradlew checkstyleMain
      - run: app/.gradlew checkstyleTest
      - uses: qltysh/qlty-action/coverage@main
        env:
          coverage-token: ${{secrets.QLTY_COVERAGE_TOKEN}}
        with:
          files: reports/coverage.xml
